apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
      purpose: ingress
      project: roboshop
      app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      purpose: ingress
      project: roboshop
      app: app1
      
  template:
    metadata:
      labels:
      purpose: ingress
      project: roboshop
      app: app1
       
    spec:
      containers:
      - name: app1
        image: vamsi74507/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  labels: 
      purpose: ingress
      project: roboshop
      app: app1
spec:
  selector:
      purpose: ingress
      project: roboshop
      app: app1
  ports:
  -  protocol: TCP
     port: 80 # service port
     targetPort: 80 # cotainer port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   labels: 
    purpose: ingress
    project: roboshop
    app: app1
   name: app1
   annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:784585544641:certificate/7a0e3d07-d4df-4897-8226-9e2b012d28f6
    alb.ingress.kubernetes.io/frontend-nlb-scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - host: "app1.daws84s.info"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80 # app1 service port
 